services:

  db:
    image: postgres:15-alpine
    container_name: albaraka_db
    networks:
      - net-albaraka_app
    environment:
      POSTGRES_DB: albaraka_test
      POSTGRES_USER: happy
      POSTGRES_PASSWORD: happy
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: albaraka-keycloak
    command: start-dev --import-realm
    networks:
      - net-albaraka_app
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak-imports:/opt/keycloak/data/import

  app:
    build:
      context: .
    container_name: albaraka_app
    networks:
      - net-albaraka_app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/albaraka_test
      SPRING_DATASOURCE_USERNAME: happy
      SPRING_DATASOURCE_PASSWORD: happy

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/albaraka
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/albaraka

    depends_on:
      - db
      - keycloak

volumes:
  pgdata:
  keycloak_data:

networks:
  net-albaraka_app:
    driver: bridge
