services:

  db:
    image: postgres:15-alpine
    container_name: albaraka_db
    networks:
      - net-albaraka_app
    environment:
      POSTGRES_DB: ${PROD_DATABASE}
      POSTGRES_USER: ${PROD_DB_USERNAME}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: albaraka-keycloak
    command: start-dev --import-realm
    networks:
      - net-albaraka_app
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8180:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak-imports:/opt/keycloak/data/import

  app:
    build:
      context: .
    container_name: albaraka_app
    networks:
      - net-albaraka_app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${PROD_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${PROD_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PROD_DB_PASSWORD}

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${JWT_ISSUER_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: ${CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI}

    depends_on:
      - db
      - keycloak

volumes:
  pgdata:
  keycloak_data:

networks:
  net-albaraka_app:
    driver: bridge
